name: 'Cache Tweaks'
description: 'Cache all enabled tweaks'
inputs:
  enable_youpip:
    required: true
  enable_ytuhd:
    required: true
  enable_ryd:
    required: true
  enable_yougroupsettings:
    required: true
  enable_yq:
    required: true
  enable_ytabconfig:
    required: true
  enable_ytweaks:
    required: true
  enable_yticons:
    required: true
  enable_demc:
    required: true
  enable_gonerino:
    required: true
  sdk_version:
    required: true
  youpip_commit:
    required: false
  ytuhd_commit:
    required: false
  ryd_commit:
    required: false
  ygs_commit:
    required: false
  yq_commit:
    required: false
  yabc_commit:
    required: false
  ytwks_commit:
    required: false
  yticons_commit:
    required: false
  demc_commit:
    required: false
  gonerino_commit:
    required: false
  ytvo_commit:
    required: false

outputs:
  cache_youpip_hit:
    description: "Cache hit status for YouPiP"
    value: ${{ steps.cache_youpip.outputs.cache-hit }}
  cache_ytuhd_hit:
    description: "Cache hit status for YTUHD"
    value: ${{ steps.cache_ytuhd.outputs.cache-hit }}
  cache_ryd_hit:
    description: "Cache hit status for Return YouTube Dislikes"
    value: ${{ steps.cache_ryd.outputs.cache-hit }}
  cache_ygs_hit:
    description: "Cache hit status for YouGroupSettings"
    value: ${{ steps.cache_ygs.outputs.cache-hit }}
  cache_yq_hit:
    description: "Cache hit status for YouQuality"
    value: ${{ steps.cache_yq.outputs.cache-hit }}
  cache_yabc_hit:
    description: "Cache hit status for YTABConfig"
    value: ${{ steps.cache_yabc.outputs.cache-hit }}
  cache_ytwks_hit:
    description: "Cache hit status for YTweaks"
    value: ${{ steps.cache_ytwks.outputs.cache-hit }}
  cache_yticons_hit:
    description: "Cache hit status for YTIcons"
    value: ${{ steps.cache_yticons.outputs.cache-hit }}
  cache_demc_hit:
    description: "Cache hit status for DontEatMyContent"
    value: ${{ steps.cache_demc.outputs.cache-hit }}
  cache_gonerino_hit:
    description: "Cache hit status for Gonerino"
    value: ${{ steps.cache_gonerino.outputs.cache-hit }}
  cache_ytvo_hit:
    description: "Cache hit status for YTVideoOverlay"
    value: ${{ steps.cache_ytvo.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Cache YouPiP
      if: inputs.enable_youpip == 'true'
      id: cache_youpip
      uses: actions/cache@v4
      with:
        path: youpip.deb
        key: youpip-${{ inputs.youpip_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YTUHD
      if: inputs.enable_ytuhd == 'true'
      id: cache_ytuhd
      uses: actions/cache@v4
      with:
        path: ytuhd.deb
        key: ytuhd-${{ inputs.ytuhd_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache Return YouTube Dislikes
      if: inputs.enable_ryd == 'true'
      id: cache_ryd
      uses: actions/cache@v4
      with:
        path: ryd.deb
        key: ryd-${{ inputs.ryd_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YouGroupSettings
      if: inputs.enable_yougroupsettings == 'true'
      id: cache_ygs
      uses: actions/cache@v4
      with:
        path: ygs.deb
        key: ygs-${{ inputs.ygs_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YouQuality
      if: inputs.enable_yq == 'true'
      id: cache_yq
      uses: actions/cache@v4
      with:
        path: yq.deb
        key: yq-${{ inputs.yq_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YTABConfig
      if: inputs.enable_ytabconfig == 'true'
      id: cache_yabc
      uses: actions/cache@v4
      with:
        path: yabc.deb
        key: yabc-${{ inputs.yabc_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YTweaks
      if: inputs.enable_ytweaks == 'true'
      id: cache_ytwks
      uses: actions/cache@v4
      with:
        path: ytwks.deb
        key: ytwks-${{ inputs.ytwks_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YTIcons
      if: inputs.enable_yticons == 'true'
      id: cache_yticons
      uses: actions/cache@v4
      with:
        path: yticons.deb
        key: yticons-${{ inputs.yticons_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache DontEatMyContent
      if: inputs.enable_demc == 'true'
      id: cache_demc
      uses: actions/cache@v4
      with:
        path: demc.deb
        key: demc-${{ inputs.demc_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache Gonerino
      if: inputs.enable_gonerino == 'true'
      id: cache_gonerino
      uses: actions/cache@v4
      with:
        path: gonerino.deb
        key: gonerino-${{ inputs.gonerino_commit }}-sdk${{ inputs.sdk_version }}

    - name: Cache YTVideoOverlay
      if: inputs.enable_yq == 'true' || inputs.enable_youpip == 'true'
      id: cache_ytvo
      uses: actions/cache@v4
      with:
        path: ytvo.deb
        key: ytvo-${{ inputs.ytvo_commit }}-sdk${{ inputs.sdk_version }}